#!/bin/bash

python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 1 --use_cube_pad true --seed 1
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 2 --use_cube_pad true --seed 1
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 3 --use_cube_pad true --seed 1

python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 1 --use_cube_pad true --seed 2
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 2 --use_cube_pad true --seed 2
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 3 --use_cube_pad true --seed 2

python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 1 --use_cube_pad true --seed 3
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 2 --use_cube_pad true --seed 3
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 3 --use_cube_pad true --seed 3

python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 1 --use_cube_pad true --seed 1 --oriented true
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 2 --use_cube_pad true --seed 1 --oriented true
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 3 --use_cube_pad true --seed 1 --oriented true

python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 1 --use_cube_pad true --seed 2 --oriented true
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 2 --use_cube_pad true --seed 2 --oriented true
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 3 --use_cube_pad true --seed 2 --oriented true

python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 1 --use_cube_pad true --seed 3 --oriented true
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 2 --use_cube_pad true --seed 3 --oriented true
python3 polynet.py --polyhedron cube --num_channels 16 --batch_size 16 --dataset 2d3ds_poly/cube_48/ --dropout_rate 0.333 --learning_rate 3e-3 --num_epochs 120 --sched_gamma 0.7 --sched_step_size 20 --task segmentation --frac_hier 0.2 --act_fn ReLU --fold 3 --use_cube_pad true --seed 3 --oriented true
